remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Drupal Hands-on Test
description: do not fork this repository, pay attention to the specs.
github:
  is_project_page: false
